apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: staging
spec:
  selector:
    app: weather-service
  ports:
  - name: http
    port: 5002
    targetPort: 5002
  type: ClusterIP
