apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-service
  template:
    metadata:
      labels:
        app: time-service
    spec:
      containers:
      - name: time-service
        image: sujjad/time-service:v1
        ports:
        - containerPort: 5001
